In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import sklearn as sns

# 세가지
# 케라스는 텐서객체를 반드시 줄 필요 없음. 시리즈 등등 가능
# 내부적으로 tensor로 바꾸는 기능이 있음
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import Adam

In [2]:
df = pd.read_csv('deeplearning_class-master/dataset/iris.csv', header = None)
#df.columns = ['Number', 'Plasma','Diastolic','Triceps','insulin','mass','pedigree','Age','Class']
df


# 1. Number of times pregnant
# 2. Plasma glucose concentration a 2 hours in an oral glucose tolerance test
# 3. Diastolic blood pressure (mm Hg)
# 4. Triceps skin fold thickness (mm)
# 5. 2-Hour serum insulin (mu U/ml)
# 6. Body mass index (weight in kg/(height in m)^2)
# 7. Diabetes pedigree function
# 8. Age (years)
# 9. Class variable (0 or 1)

0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       150 non-null    float64
 1   1       150 non-null    float64
 2   2       150 non-null    float64
 3   3       150 non-null    float64
 4   4       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [4]:
# sns.pairplot(df, hue= 'species')
# plt.show()

In [5]:
dataset = df.values
dataset

array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Iri

In [6]:
X = dataset[:,0:4].astype(float)
y_obj = dataset[:,4]
y_obj

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

## 데이터 프레임 전처리 1

In [7]:
e = LabelEncoder()
e.fit(y_obj)
Y=e.transform(y_obj)
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# 데이터 프레임 전처리2

In [8]:
# pd.merge()

## One-Hot encoding

In [9]:
Y_encoded = tf.keras.utils.to_categorical(Y)
Y_encoded

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

## One-Hot encoding 2

In [10]:
Y_encoded = tf.one_hot(Y, depth=3).numpy()
Y_encoded

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [16]:
# Dense 개체 생성
# units 는 출력 개수, 혹은 라벨의 개수
# input_dim은 feature의 개수


IO = Dense(units=1, input_dim=4)


# 리스트로 주어야 함
# sequential 순차적 구조로 Dense를 쌓아 올림 => 여러개 쌓아올릴 경우 딥러닝
model = Sequential( [IO] )
model.add(Dense(16, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))

# loss는 cost랑 동일
# Adam의 러닝메이트 = 0.1 -> 러닝메이트 스스로 조절 가능
# optimizer의 종류는 매우 다양함
model.compile( loss = 'categorical_crossentropy', optimizer = Adam(0.1), metrics=['accuracy'] )



#epochs = 학습 횟수
h = model.fit(X, Y_encoded, epochs = 15, batch_size=10)

Epoch 1/15
15/15 [==============================] - 0s 804us/step - loss: 1.3225 - accuracy: 0.4333
Epoch 2/15
15/15 [==============================] - 0s 1ms/step - loss: 0.4291 - accuracy: 0.7800
Epoch 3/15
15/15 [==============================] - 0s 1ms/step - loss: 0.2775 - accuracy: 0.9000
Epoch 4/15
15/15 [==============================] - 0s 1ms/step - loss: 0.3769 - accuracy: 0.8067
Epoch 5/15
15/15 [==============================] - 0s 1ms/step - loss: 0.2518 - accuracy: 0.8867
Epoch 6/15
15/15 [==============================] - 0s 1ms/step - loss: 0.1369 - accuracy: 0.9600
Epoch 7/15
15/15 [==============================] - 0s 1ms/step - loss: 0.1416 - accuracy: 0.9333
Epoch 8/15
15/15 [==============================] - 0s 1ms/step - loss: 0.1776 - accuracy: 0.9333
Epoch 9/15
15/15 [==============================] - 0s 1ms/step - loss: 0.2317 - accuracy: 0.8933
Epoch 10/15
15/15 [==============================] - 0s 1ms/step - loss: 0.2443 - accuracy: 0.9067
Epoch 11/15
15/15

In [18]:
wb = IO.get_weights()
wb

[array([[ 0.38045886],
        [ 1.1622856 ],
        [-1.3333474 ],
        [-2.2739499 ]], dtype=float32),
 array([1.4601697], dtype=float32)]

In [19]:
# 최종 w값
# float(wb[0])

TypeError: only size-1 arrays can be converted to Python scalars

In [21]:
# 최종 b값
float(wb[1])

1.4601696729660034

In [22]:
# loss키를 줄 경우 cost값 확인 가능
h.history['loss']

[1.3224735260009766,
 0.4291025698184967,
 0.2774798572063446,
 0.3768605589866638,
 0.2517939805984497,
 0.13685734570026398,
 0.1416451334953308,
 0.17755594849586487,
 0.23172399401664734,
 0.24426941573619843,
 0.10392694175243378,
 0.07588564604520798,
 0.0766105055809021,
 0.2422659993171692,
 0.17420068383216858]

In [ ]:
plt.plot(h.history['loss'])
plt.show

In [ ]:
# 예측값 추정
model.predict( [94] )

In [ ]:
plt.scatter(df['insulin'], df['Class'])