In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
# 세가지
# 케라스는 텐서객체를 반드시 줄 필요 없음. 시리즈 등등 가능
# 내부적으로 tensor로 바꾸는 기능이 있음
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import Adam
import numpy as np

seed=0
np.random.seed(seed)
tf.random.set_seed(3)

In [10]:
df1 = pd.read_csv('deeplearning_class-master/dataset/wine.csv', header = None)
#df.columns = ['Number', 'Plasma','Diastolic','Triceps','insulin','mass','pedigree','Age','Class']
df1 = df1.sample(frac=1)


# 1. Number of times pregnant
# 2. Plasma glucose concentration a 2 hours in an oral glucose tolerance test
# 3. Diastolic blood pressure (mm Hg)
# 4. Triceps skin fold thickness (mm)
# 5. 2-Hour serum insulin (mu U/ml)
# 6. Body mass index (weight in kg/(height in m)^2)
# 7. Diabetes pedigree function
# 8. Age (years)
# 9. Class variable (0 or 1)

In [3]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       6497 non-null   float64
 1   1       6497 non-null   float64
 2   2       6497 non-null   float64
 3   3       6497 non-null   float64
 4   4       6497 non-null   float64
 5   5       6497 non-null   float64
 6   6       6497 non-null   float64
 7   7       6497 non-null   float64
 8   8       6497 non-null   float64
 9   9       6497 non-null   float64
 10  10      6497 non-null   float64
 11  11      6497 non-null   int64  
 12  12      6497 non-null   int64  
dtypes: float64(11), int64(2)
memory usage: 660.0 KB


In [11]:
df = df1.values
df

array([[ 6.3 ,  0.18,  0.24, ...,  9.2 ,  6.  ,  0.  ],
       [ 6.8 ,  0.14,  0.18, ..., 11.2 ,  6.  ,  0.  ],
       [ 7.3 ,  0.22,  0.5 , ...,  9.  ,  6.  ,  0.  ],
       ...,
       [ 6.8 ,  0.2 ,  0.59, ...,  9.1 ,  6.  ,  0.  ],
       [ 6.6 ,  0.22,  0.37, ..., 10.3 ,  7.  ,  0.  ],
       [ 8.7 ,  0.22,  0.42, ..., 10.  ,  5.  ,  0.  ]])

In [12]:
X = df[:,:12]
X

array([[ 6.3 ,  0.18,  0.24, ...,  0.52,  9.2 ,  6.  ],
       [ 6.8 ,  0.14,  0.18, ...,  0.54, 11.2 ,  6.  ],
       [ 7.3 ,  0.22,  0.5 , ...,  0.66,  9.  ,  6.  ],
       ...,
       [ 6.8 ,  0.2 ,  0.59, ...,  0.38,  9.1 ,  6.  ],
       [ 6.6 ,  0.22,  0.37, ...,  0.55, 10.3 ,  7.  ],
       [ 8.7 ,  0.22,  0.42, ...,  0.43, 10.  ,  5.  ]])

In [13]:
Y = df[:,12]
Y

array([0., 0., 0., ..., 0., 0., 0.])

In [16]:


# 리스트로 주어야 함
# sequential 순차적 구조로 Dense를 쌓아 올림 => 여러개 쌓아올릴 경우 딥러닝
model = Sequential()
model.add(Dense(30, input_dim=12, activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(18, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# loss는 cost랑 동일
# Adam의 러닝메이트 = 0.1 -> 러닝메이트 스스로 조절 가능
# optimizer의 종류는 매우 다양함
model.compile( loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'] )



#epochs = 학습 횟수
h = model.fit(X, Y, epochs = 200, batch_size=200)
model.evaluate(X, Y)

Epoch 1/200
33/33 [==============================] - 0s 1ms/step - loss: 0.2588 - accuracy: 0.9097
Epoch 2/200
33/33 [==============================] - 0s 1000us/step - loss: 0.2222 - accuracy: 0.9272
Epoch 3/200
33/33 [==============================] - 0s 1ms/step - loss: 0.2098 - accuracy: 0.9283
Epoch 4/200
33/33 [==============================] - 0s 1ms/step - loss: 0.2058 - accuracy: 0.9295
Epoch 5/200
33/33 [==============================] - 0s 1ms/step - loss: 0.1979 - accuracy: 0.9326
Epoch 6/200
33/33 [==============================] - 0s 1ms/step - loss: 0.1912 - accuracy: 0.9346
Epoch 7/200
33/33 [==============================] - 0s 1ms/step - loss: 0.1858 - accuracy: 0.9369
Epoch 8/200
33/33 [==============================] - 0s 1ms/step - loss: 0.1816 - accuracy: 0.9374
Epoch 9/200
33/33 [==============================] - 0s 1ms/step - loss: 0.1750 - accuracy: 0.9395
Epoch 10/200
33/33 [==============================] - 0s 1ms/step - loss: 0.1668 - accuracy: 0.9438
Epoch 

[0.03421550616621971, 0.9915345311164856]

In [17]:
model.evaluate(X,Y)

204/204 [==============================] - 0s 804us/step - loss: 0.0342 - accuracy: 0.9915


[0.03421550616621971, 0.9915345311164856]